apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    version: 1
    apiVersion: 1
    orgId: 1
    url: http://${TEMPO_ADDR}
    basicAuth: false
    isDefault: true
    editable: false

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    version: 1
    apiVersion: 1
    orgId: 1
    url: http://${PROMETHEUS_ADDR}
    basicAuth: false
    isDefault: false
    editable: false